name: cron

on:

  workflow_dispatch:

  schedule:

    - cron: "* */24 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  cron:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - uses: actions/checkout@v4
      - name: cron
        run: python -c "import os; os.chdir('.epg'); import service"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New EPG DATA
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
